export const UPLOAD_LEAVE_INFO = 'UPLOAD_LEAVE_INFO';

export const REQUEST_LEAVE_INFO = 'REQUEST_LEAVE_INFO';

export const GET_LEAVE_INFO = 'GET_LEAVE_INFO';

export const GET_APPROVED_INFO = 'GET_APPROVED_INFO';

export const NEW_LEAVE_UPDATE = 'NEW_LEAVE_UPDATE';

